### ISSUE TITLE
Fails to update with NavigationView sidebar toggling on iPad

### ISSUE THREAD

**Issue by aehlke** [tgrapperon/swiftui-layout-guides#1]
Using fitToReadableContentWidth, toggling the sidebar on iPad doesn't update padding until the screen is otherwise re-rendered after user interaction

(Otherwise great lib!)

**Comment by tgrapperon** [comment]
Hey @aehlke! Thanks for the report. I've pushed a temporary fix in [v0.0.4](https://github.com/tgrapperon/swiftui-layout-guides/releases/tag/0.0.4).

**Comment by aehlke** [comment]
Amazing thank you so much
