### ISSUE TITLE
Navigation title alignment

### ISSUE THREAD

**Issue by aehlke** [tgrapperon/swiftui-layout-guides#4]
Here's another one I'm working on via `UINavigationBar.appearance(whenContainedInInstancesOf ...)` and a hosting container - insetting large navigation titles to match the readable content guide. I may have a solution (just having issues with it updating after initial setting) but not integrated into this library.

**Comment by tgrapperon** [comment]
I'm not sure this ones fits within the reach of this library. 
But feel free to post some code showing the problem so we can discuss.

**Comment by aehlke** [comment]
Understood, I'll share my solution

**Comment by aehlke** [comment]
abandoned, couldn't get working
